version: "3.9"

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: git-manager-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./frontend
    container_name: git-manager-frontend
    environment:
      - VITE_API_URL=http://backend:5000
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always